### ISSUE TITLE
missing message 

### ISSUE THREAD

**Issue by roniRamon** [roniRamon/big-project#9]
when finishing a story and the player go back to the city 
whats the message that he see??

**Comment by goshasawicka** [comment]
I think it should return to the cross-path page where there are options to go to all locations (with validation that location is visible only if the penguin from that location is not collected). If all penguins are collected then Pythons Nest should be the only one remaining.

**Comment by goshasawicka** [comment]
I have added in the tech spec logic that if penguin from that region is 0 then only this location can be visible (because it means that we have finished all events in that section) will add additional page at the end of each section where penguin will be found. - changes in commit: "issue "missing message #9"" 4c345aa
